name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: latest
          spago: latest

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: |
          yarn install --ignore-optional
          spago install
          spago --config generator-spago.dhall install
          spago --config examples-spago.dhall install

      - name: Build source
        run: |
          spago build --no-install
          spago --config generator-spago.dhall build --no-install

      - name: Run tests
        run: ./ci-approve.sh
